(import (chicken bitwise)
        (chicken format)
        (chicken pathname)
        (chicken process-context)
        (chicken random))

(define (gol X Y I N)
  "init vector"
  (let ((uni (make-vector X)))
    (do ((x 0 (add1 x))) ((= x X))
      (vector-set! uni x (make-vector Y))
      (do ((y 0 (add1 y))) ((= y Y))
        (vector-set! (vector-ref uni x) y (make-vector 2 0))))
    (do ((i 0 (let ((x (pseudo-random-integer X))
                    (y (pseudo-random-integer Y)))
                (if (zero? (vector-ref (vector-ref (vector-ref uni x) y) 0))
                    (begin
                      (vector-set! (vector-ref (vector-ref uni x) y) 0 1)
                      (add1 i))
                    i))))
      ((= i I)))
    "run the game of life"
    (set! flag 0)
    (do ((n 0 (add1 n))) ((= n N))
      (printf "P1\n~a ~a\n" Y X)
      (set! neg (bitwise-xor flag 1))
      (do ((x 0 (add1 x))) ((= x X))
        (do ((y 0 (add1 y))) ((= y Y))
          (printf "~a" (vector-ref (vector-ref (vector-ref uni x) y) flag))
          "count neighbors"
          (set! cnt 0)
          (do ((u -1 (add1 u))) ((> u 1))
            (do ((v -1 (add1 v))) ((> v 1))
              (unless (and (zero? u)
                           (zero? v))
                (set! cnt (+ cnt (vector-ref (vector-ref (vector-ref uni (remainder (+ x u X) X))
                                                                         (remainder (+ y v Y) Y))
                                                                         flag))))))
          (case cnt
            ((2)  (set! tmp (vector-ref (vector-ref (vector-ref uni x) y) flag)))
            ((3)  (set! tmp 1))
            (else (set! tmp 0)))
          (vector-set! (vector-ref (vector-ref uni x) y) neg tmp)))
      (set! flag neg))))

"argument parsing"
(let ((lst (command-line-arguments)))
  (if (= (length lst) 4)
      (do ((lst (reverse lst) (cdr lst))
           (acc (list) (let* ((cur (car lst))
                              (num (string->number cur)))
                         (if (or (not num)
                                 (< num 0))
                             (begin
                               (format (current-error-port)
                                       "error : '~a' isn't a valid positive integer\n"
                                       cur)
                               (exit 1))
                             (cons num acc)))))
        ((null? lst) (apply gol acc)))
      (begin
        (format (current-error-port)
                "usage : ~a [height] [width] [init] [iter]\n"
                (pathname-file (program-name)))
        (exit 1))))
