#!/usr/bin/env bash

X=20  # vertical grid size
Y=40  # horizontal grid size
I=200 # attempts at creating live cells

declare -A gol cpy

for ((; i++ < I;)) do
    ((
        x = RANDOM % X,
        y = RANDOM % Y,

        gol[$x $y] = 1
    ))
done

check()
{
    c=

    for ((x = i - 1; x <= i + 1; x++)) do
        ((
            gol[$x $((j - 1))] && c++,
            gol[$x $((j + 1))] && c++
        ))
    done

    ((
        gol[$((i - 1)) $j] && c++,
        gol[$((i + 1)) $j] && c++
    ))
}

update()
{
    p=

    for ((i = 0; i < X; i++)) do
        for ((j = 0; j < Y; j++)) do
            ((gol[$i $j])) && p+=. || p+=' '

            check

            case $c in
                2) ;; # do nothing
                3) cpy[$i $j]=1;;
                *) cpy[$i $j]=0
            esac
        done

        p+='\n'
    done

    printf '\e[H%b' "$p"

    for i in "${!cpy[@]}"; do
        gol[$i]=${cpy[$i]}
    done
}

printf '\e[2J'

for ((;;)) do
    update
done
