#!/usr/bin/env bash

Y=20  # grid width
X=20  # grid height
I=300 # attempts at creating live cells

check() {
    ((c = gol[$i $j] ? -1 : 0))

    for x in -1 0 1; do
        for y in -1 0 1; do
            ((
                a = i + x < 0 ? X - 1 : (i + x) % X,
                b = j + y < 0 ? Y - 1 : (j + y) % Y
            ))

            ((gol[$a $b] && c++))
        done
    done
}

update() {
    p=

    for ((i = 0; i < X; i++)) do
        for ((j = 0; j < Y; j++)) do
            ((gol[$i $j])) && p+='. ' || p+='  '

            check

            case $c in
                2) ;; # do nothing
                3) cpy[$i $j]=1;;
                *) cpy[$i $j]=0
            esac
        done

        p+='\n'
    done

    printf '\e[H%b' "$p"

    for i in "${!cpy[@]}"; do
        gol[$i]=${cpy[$i]}
    done
}

declare -A gol cpy

trap $'printf \e[?25h' EXIT

for ((; i++ < I;)) do
    ((
        x = RANDOM % X,
        y = RANDOM % Y,

        gol[$x $y] = 1
    ))
done

printf '\e[2J\e[?25l'

for ((;;)) { update; }
