#!/bin/sh

_()
    if ! command "$1" > /dev/null; then
        echo "error : install $1 first" >&2
        exit 1
    fi

_ mpv
_ wattr

./make.sh

# run based on screen resolution
wattr hw "$(lsw -r)" | {
    read -r h w

    ./pinwheels    \
        $((h / 2)) \
        $((w / 2)) \
        $((h * w / 4))
} |
    mpv - -fs -scale=nearest

