#!/bin/sh

if ! command -v mpv > /dev/null; then
    echo 'error : install mpv first' >&2
    exit 1
if

./make.sh

wattr hw "$(lsw -r)" | {
    read -r h w

    ./pinwheels    \
        $((h / 2)) \
        $((w / 2)) \
        $((h * w / 4))
} |
    mpv - -fs -scale=nearest

