#!/usr/bin/env bash
#
# generate xbm files

set -e

(($# != 3)) && {
    printf 'usage : gen [rule] [width] [height]\n' >&2
    exit 1
}

test -x automaton ||
    ./make.sh &> /dev/null

mkdir -p etc

{
    mapfile -t input

    printf '#define _width %04s\n' "$2"
    printf '#define _height%04s\n' "$3"
    printf 'static unsigned char _bits[] = {\n'

    for ((; i < $3; i++)) {
        for ((j = 0; j < $2; j += 8)) {
            tmp=${input[i]:j:8}

            eval printf -v tmp %s \${tmp:{7..0}:1}

            printf -v tmp '0x%02x' $((2#$tmp))

            ((i + 1 < $3 || j + 8 < $2)) &&
                printf '%s, '   "$tmp" ||
                printf '%s\n};' "$tmp"
        }
    }
} < <(
    while read -r line; do
        printf '%s\n' "${line:${#line} - $2 - 2:$2}"
    done < <(
        {
            mapfile -t input

            printf '%s\n' "${input[@]:${#input[@]} - $3:$3}"
        } < <(
            ./automaton "$1" $(
                for ((; i++ < $2 * 2;)) {
                    printf '%s' $((RANDOM % 2))
                }
            )))) > "etc/$1.xbm"
