#!/usr/bin/env bash
#
# outputs to mpv

./make.sh

./1d $((RANDOM % 256)) \
    "$(
        for _ in {1..500}; {
            echo -n $((RANDOM % 2))
        }
    )" |
        mpv - -fs -scale=nearest
