#!/usr/bin/env bash

# check for mpv
if ! command -v mpv > /dev/null; then
    echo 'error : install mpv first' >&2
    exit 1
fi

./make.sh

# set a random rule and a random init
./1d $((RANDOM % 256)) \
    "$(
        for _ in {1..500}; {
            echo -n $((RANDOM % 2))
        }
    )" |
        mpv - -fs -scale=nearest
