#!/usr/bin/env bash
#
# outputs to mpv

if ! command -v mpv > /dev/null; then
    echo 'error : install mpv first' >&2
    exit 1
if

./make.sh

./1d $((RANDOM % 256)) \
    "$(
        for _ in {1..500}; {
            echo -n $((RANDOM % 2))
        }
    )" |
        mpv - -fs -scale=nearest
