#!/usr/bin/env bash
#
# life - game of life implementation

cd "${0%.*}"; . ../main

usage="usage : ${0##*/} [height] [width] [init] [iter]"

helper X "$1"
helper Y "$2"
helper I "$3"
helper N "$4"

declare -A uni

((t = 0))

for ((i = 0; i < I; ++i)) {
    ((
        x = RANDOM % X,
        y = RANDOM % Y
    ))

    ((uni[$x $y $t] = 1))
}

for ((n = 0; n < N; ++n)) {
    out="P1\n$X $Y\n"

    for ((i = 0; i < X; ++i)) {
        for ((j = 0; j < Y; ++j)) {
            out+=$((uni[$i $j $t]))

            ((cnt = 0))

            for u in -1 0 1; {
                for v in -1 0 1; {
                    ((u != 0 || v != 0)) && {
                        ((
                            x = (i + u + X) % X,
                            y = (j + v + Y) % Y
                        ))

                        ((uni[$x $y $t] == 1 && ++cnt))
                    }
                }
            }

            case $cnt in
                2) ((tmp = uni[$i $j $t]));;
                3) ((tmp = 1));;
                *) ((tmp = 0));;
            esac

            ((uni[$i $j $((!t))] = tmp))
        }
    }

    printf '%b\n' "$out"

    ((t ^= 1))
}
