#!/usr/bin/env bash
#
# life - game of life implementation

X=20
Y=20
I=150

declare -A gol cpy

for ((; i++ < I;)) {
    ((
        x = RANDOM % X,
        y = RANDOM % Y,

        gol[$x $y] = 1
    ))
}

printf '\e[2J\e[?25l'
trap $'printf \e[?25h' EXIT

for ((;;)) {
    out='\e[H'

    for ((i = 0; i < X; i++)) {
        for ((j = 0; j < Y; j++)) {
            ((gol[$i $j])) && out+='# ' || out+='  '

            cnt=0

            for a in -1 0 1; {
                for b in -1 0 1; {
                    ((a || b)) && {
                        ((
                            x = (X + i + a) % X,
                            y = (Y + j + b) % Y
                        ))

                        ((gol[$x $y] && cnt++))
                    }
                }
            }

            case $cnt in
                2) ;; # do nothing
                3) cpy[$i $j]=1;;
                *) cpy[$i $j]=0
            esac
        }

        out+='\n'
    }

    printf '%b' "$out"

    for i in "${!cpy[@]}"; do
        gol[$i]=${cpy[$i]}
    done
}
